name: Run Tidy

on:
  push:
    paths-ignore:
      - '.github/workflows/build_sp.yml'
      - '.github/workflows/build_tools.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/build_sp.yml'
      - '.github/workflows/build_tools.yml'

jobs:
  tidy:
    name: Run Tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Tidy
        working-directory: ./tools/tidy
        run: python3 main.py check_all
